# Generated by Django 4.1.1 on 2022-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chandelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, unique=True, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleLamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_switched_on', models.BooleanField(blank=True, default=False, verbose_name='On/Off Flag')),
                ('address', models.CharField(help_text='Unique device address', max_length=200, unique=True, verbose_name='Address')),
                ('lamp_type', models.IntegerField(choices=[(1, 'Led'), (2, 'Halogen'), (3, 'Common'), (4, 'Flourescent')], verbose_name='Type')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Power')),
                ('colorful_temperature', models.IntegerField(blank=True, null=True, verbose_name='Color Temperature')),
                ('voltage', models.IntegerField(blank=True, null=True, verbose_name='Supply Voltage')),
                ('chandelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', related_query_name='%(app_label)s_%(class)ss', to='dummy.chandelier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimmableLamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_switched_on', models.BooleanField(blank=True, default=False, verbose_name='On/Off Flag')),
                ('address', models.CharField(help_text='Unique device address', max_length=200, unique=True, verbose_name='Address')),
                ('lamp_type', models.IntegerField(choices=[(1, 'Led'), (2, 'Halogen'), (3, 'Common'), (4, 'Flourescent')], verbose_name='Type')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Power')),
                ('colorful_temperature', models.IntegerField(blank=True, null=True, verbose_name='Color Temperature')),
                ('voltage', models.IntegerField(blank=True, null=True, verbose_name='Supply Voltage')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Brightness Level')),
                ('chandelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', related_query_name='%(app_label)s_%(class)ss', to='dummy.chandelier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
